### ISSUE TITLE
move "\Orchestra\Testbench\" to use statement on the top in /tests/TestCase.php

### ISSUE THREAD

**Issue by inaydich** [CU-CommunityApps/CD-LaravelStarterKit#44]
https://github.com/CU-CommunityApps/CD-LaravelStarterKit/blob/7f13adbe3a2b834de5e543ae6d5a7b2168964539/tests/TestCase.php#L7

I think moving "\Orchestra\Testbench\" to use statement is better for code readability. Some people online also claim that it also improves some performance.

**Comment by woodseowl** [comment]
I'm in agreement that any time you can apply a `use` statement you should, for the reasons you mention. (And PhpStorm provides inline reminders and helpers for it and does it very automatically, which is fantastic.) 

This is an unusual case, because the class being extended has the same name as the class being defined. The solution you are suggesting would require either renaming `tests/TestCase.php` or defining the `use` statement for `\Orchestra\Testbench\TestCase` with an alias.

I think all three options are style choices. I considered them all when I first extended the \Orchestra\Testbench\TestCase in this class. I don't know of a convention or style guide that we would use for this, so I think that means it's up to the author of the code to make the choice that seems best to them.

I'd like to close this issue based on this rationale, unless you have additional thoughts?

**Comment by inaydich** [comment]
I think using alias is fine in this case

**Comment by woodseowl** [comment]
Perhaps the comment that opened up the discussion of ownership is when I said "it's up to the author of the code." I meant "author" only in the context of the pull request at the time the code was introduced. Basically, someone has to make a decision at the moment the code is written and, when it is a style choice, "the author" should do what makes the most sense to them.

I do appreciate the call-out and hope I'm being open! Shared ownership is a principle I wholeheartedly embrace and have practiced at great length with many teams. There are definitely moments it takes humility!

I put in a PR that I think applies what you recommended?

**Comment by woodseowl** [comment]
Ack, I didn't mean for this to automatically close!

**Comment by inaydich** [comment]
I think I indicated sound reasons for the change.  I was surprised to hear back "it's up to the author of the code to make the choice that seems best to them."  I do not think it is a convincing argument. 
Closing the issue now is fine with me. Thanks for re-considering your decision.
